/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salvadorenrollmentsystem;

/**
 *
 * @author seans
 */
public class ManageTeachers extends javax.swing.JFrame {

    /**
     * Creates new form ManageTeachers
     */
    public ManageTeachers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addTeachers = new javax.swing.JButton();
        editTeachers = new javax.swing.JButton();
        deleteTeachers = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        viewTeachers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 467));
        setMinimumSize(new java.awt.Dimension(640, 467));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Manage Teachers");

        addTeachers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addTeachers.setText("Sign Up a New Teachers");
        addTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeachersActionPerformed(evt);
            }
        });

        editTeachers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editTeachers.setText("Edit Teachers Details");
        editTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTeachersActionPerformed(evt);
            }
        });

        deleteTeachers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteTeachers.setText("Remove a Teacher");
        deleteTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeachersActionPerformed(evt);
            }
        });

        exitButton.setText("Back to main menu");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        viewTeachers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewTeachers.setText("View All Teachers");
        viewTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeachersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deleteTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(viewTeachers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addTeachers)
                .addGap(28, 28, 28)
                .addComponent(editTeachers)
                .addGap(29, 29, 29)
                .addComponent(deleteTeachers)
                .addGap(35, 35, 35)
                .addComponent(exitButton)
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeachersActionPerformed
        // TODO add your handling code here:
        this.show(false);
        AddTeacher at = new AddTeacher();
        at.setVisible(true);
    }//GEN-LAST:event_addTeachersActionPerformed

    private void editTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTeachersActionPerformed
        // TODO add your handling code here:
        this.show(false);
        EditTeacher et = new EditTeacher();
        et.setVisible(true);
    }//GEN-LAST:event_editTeachersActionPerformed

    private void deleteTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeachersActionPerformed
        // TODO add your handling code here:
        this.show(false);
        RemoveTeacher rt = new RemoveTeacher();
        rt.setVisible(true);
    }//GEN-LAST:event_deleteTeachersActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.show(false);
        StartMenu sm = new StartMenu();
        sm.setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void viewTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeachersActionPerformed
        // TODO add your handling code here:
        this.show(false);
        ViewTeachers vt = new ViewTeachers();
        vt.setVisible(true);
    }//GEN-LAST:event_viewTeachersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeachers;
    private javax.swing.JButton deleteTeachers;
    private javax.swing.JButton editTeachers;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewTeachers;
    // End of variables declaration//GEN-END:variables
}
